### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by shailendrabhatt1991** [ghorbanzadeh/OWAAT#2]
when i m going to login .it will display following error:
#2110 - A User Is Logged In!

and how to get correct  credentials what is process for that

**Comment by n0x00** [comment]
it's in sc.php```<?php
$sc = '3mcudalxn7ftq3974kk4dzsbfkli2j'; //Security Code.
$time = '1485249399';//It is valid for 10 minutes.
?> ```
